version: '3.8'

services:
  app:
    image: ngbilling-gestao-bancaria:latest
    build: .
    container_name: ng_billing_app
    environment:
      - DB_URL=jdbc:postgresql://db:5432/ngbilling
      - DB_USER=postgres
      - DB_PASSWORD=postgresql
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: ng_billing_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: ngbilling
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
